<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Page</h1>

        <button type="button" class="download-file">Download the document</button>


        <script>
        var PDF_DOWNLOAD_URL = "{{ urlFor('PDFDownload') }}";
        $(function(){
            //Your old way
            $("button.download-file").click(function(){
                $.ajax({
                    method: "GET",
                    url: PDF_DOWNLOAD_URL,
                    headers: { 'x-my-custom-header': 'some value' },
                    success: function(data){
                        console.log("Data received:", data);
                    }
                });
            });

        });
        </script>
    </body>
</html>
